### PR TITLE
Added support for single flow connections

### PR DESCRIPTION
**Pull request by mangilimicprinceton**
Rather than raising a NotImplementedException("one flow connection not supported yet"), I added the support for single flow connections.

I hope this change can improve captcp.

### CODE REVIEW

**Comment by hgn** [comment]
Hey Michele,

the patch looks great! Thanks for the contribution. I will check the patch today and will merge if everything works as expected.

**Comment by mangilimicprinceton** [comment]
Hi Hagen,

Awesome! Thank you for considering this contribution!

Best,
Michele

**Comment by hgn** [comment]
Merged, thank you very much Michele!

**Comment by mangilimicprinceton** [comment]
Thank you Hagen for providing us with this software!

Best,
Michele

**Pull request merged**
