### PR TITLE
adding data-ack-spacing mod

### PR DESCRIPTION
**Pull request by danielmgit**

### CODE REVIEW

**Comment by danielmgit** [comment]
Test-file: 
[dump_gamma.zip](https://github.com/hgn/captcp/files/304730/dump_gamma.zip)

**Comment by hgn** [comment]
Any ideas how to output the results? We can print a line graph (y axis the response time), we can print statistic graphs and finally we can output the data for later analysis for many tcp connections.

```
--mode <time-graph | statistics-graph | batch >
```

**Comment by danielmgit** [comment]
My suggestion would also have been a line graph where the response time is on the y axis. Your further suggestion also sound pretty usefull.

**Comment by danielmgit** [comment]
Updated merge-request. The mode selection/description got somewhat lost. Now it should be fine.

**Pull request merged**
