### PR TITLE
 Use setup.py for install, create a package to handle datafiles

### PR DESCRIPTION
**Pull request by mrueg**
When I tried to package captcp, I had some issues because of the mixed install process and the directories the data files got installed to.
This pull request creates a python package and moves the files in data and the original captcp.py to it. 
In future it should be possible to split catcp.py into separate python modules.
In addition I removed the Makefile and let setup.py handle the full install.

### CODE REVIEW

**Comment by hgn** [comment]
Hey Manuel! Thank you for the work. Sorry for the delay - I will check you patch, primary because some guys already build some distro packages.

**Comment by hgn** [comment]
One short question: now that the Makefile is gone. How do I install captcp? What are the steps to do so?

**Comment by mrueg** [comment]
"python setup.py install" should be sufficient to install it. 
Unfortunately you can't run it from tarball now, because python does not know about the module.
Please don't merge the pull request right now, I might have a solution for that.

**Comment by hgn** [comment]
Great, I wait!

**Pull request closed without merging**
